version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: ls -alR lib/go-fdkaac/fdkaac-lib/libAACdec/src > depseed
      - restore_cache:
          keys:
            - fdkaac-lib-artifact-{{ checksum "depseed" }}
      - run: make
      - save_cache:
          key: fdkaac-lib-artifact-{{ checksum "depseed" }}
          paths:
            - lib/go-fdkaac/fdkaac-lib-objs

workdlows:
  build:
    jobs:
      - build

