version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: make dep
      - run: (cd lib/go-fdkaac/fdkaac-lib && git rev-parse HEAD) | tee libfdk-deps-checksum
      - run: echo $CACHE_VERSION | tee cache-version
      - restore_cache:
          keys:
            - fdkaac-lib-artifact-{{ checksum "libfdk-deps-checksum" }}-{{ checksum "cache-version" }}
      - run: make
      - save_cache:
          key: fdkaac-lib-artifact-{{ checksum "libfdk-deps-checksum" }}-{{ checksum "cache-version" }}
          paths:
            - lib/go-fdkaac/fdkaac-lib

workdlows:
  build:
    jobs:
      - build

