version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: make

workdlows:
  build:
    jobs:
      - build

